
# Name your project! Project names should be lowercase and use underscores as separators
# See documentation: https://docs.getdbt.com/docs/build/projects

name: 'dbt_snowflake_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_snowflake'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/build/projects

models:
  dbt_snowflake_project:
    # Config indicated by + and applies to all files under models/
    +materialized: view
    +schema: analytics
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

# Seedlings
seeds:
  dbt_snowflake_project:
    +schema: seeds

vars:
  # Example variables
  environment: 'dev'
  start_date: '2020-01-01'
